server:
  port: 80

spring:
  datasource:
    #mysql版本为8.0.13
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/nrsc_security?characterEncoding=utf-8&serverTimezone=GMT&useSSL=false
    username: root
    password: 123456

nrsc:
  security:
    code:
      image:
        length: 6 #图形验证码的位数为6，将覆盖默认配置中的4
        width: 100 #图形验证码的宽度为100，将覆盖默认配置中的67，但由于请求中设置的宽度为200，所以真正的宽度将为200
        urls: /hello,/me*
    browser:
      loginPage: /nrsc-login.html
      loginType: JSON
    social:
      qq:
        app-id: 100550231
        app-secret: 69b6ab57b22f3c2fe6a6149274e3295e
        providerId: callback.do
      filterProcessesUrl: /qqLogin




